### PR TITLE
Hotfix: Serial Interface Memory Error

### PR DESCRIPTION
**Pull request by RKLindsey**
## Items to be completed prior to PR review

- [N/A] Requested `develop` as target branch
- [x] Attached test suite log file
- [N/A] Alerted reviewers if edits impact CMake or Makefile files

This commit fixes issue #67, and has been tested on the provided issue example files.

This commit also adds a new parameter file for C/N systems, for the transfer learning paper. 

[run_tests-short.log](https://github.com/rk-lindsey/chimes_calculator/files/15349850/run_tests-short.log)

### CODE REVIEW

**Comment by RKLindsey** [comment]
@shihkual This should fix your issue - please give it a try and let me know.

**Comment by RKLindsey** [comment]
[shihkual](https://github.com/shihkual) this should fix your issue!

**Comment by rk-lindsey** [comment]
@aradi There seems to be an issue with the CI / gnu-build (macos-latest, 11) action, unrelated to the code - see attached log file. Could you please advise?
[logs_23899123545.zip](https://github.com/rk-lindsey/chimes_calculator/files/15350285/logs_23899123545.zip)

**Comment by shihkual** [comment]
@rk-lindsey Thanks! I will give it a try and report the results to you.

**Comment by shihkual** [comment]
@rk-lindsey I have done the test. The hotfix is working, and my simulation is running for 48 hours without an OOM error. Just a little reminder that users need to rebuild the **`chimes_calculator`** after they clone the repo to their machine to install the hotfix by running `./install.sh`.

**Comment by aradi** [comment]
That's a problem with the MacOS workflow. I have fixed it in #70.

**Review by rk-lindsey — APPROVED** [review]

**Pull request merged**
