### PR TITLE
Bugfixes:

### PR DESCRIPTION
**Pull request by RKLindsey**
- CMakeLists.txt was incompatible with test suite (didn't produce executables)
- Default was config.cmake options incompatible with test suite/standard builds
- Fixes broken install.sh (relied on CMake)
- Default install.sh build location changed back to "build"

This **does** impact CMake files
[run_tests.log](https://github.com/rk-lindsey/chimes_calculator/files/7737151/run_tests.log)

## Pull request template

- N/A: Requested `develop` as target branch
- [x] Attached test suite log file
- [x] Alerted reviewers if edits impact CMake or Makefile files

### CODE REVIEW

**Comment by RKLindsey** [comment]
@nirgoldman @aradi 

This draft PR centers around making CMake produce the expected `chimes_calculator` executables. They should be produced by running the install script (`install.sh`) and accessible to the  test suite, i.e. `/serial_interface/tests/run_tests.sh`. 

My edits pass all our test suite checks (see log file attached in the top comment), but not the CI. 

@aradi - I'd appreciate your input on my CMakeLists.txt edits, which look to have broken the CI.

**Comment by aradi** [comment]
@RKLindsey Note, the executables should use ChIMES functionality through the libraries. By letting them depend on both, the compiled library and the source files, you have created unnecessary (and circular dependencies). I've fixed that in RKLindsey/chimes_calculator#9, which you can just merge into your feature branch in this PR.

A few other things to note:
* You should not specifiy any compiler flags, which CMake will automatically add correctly anyway (e.g. `-fPIC`). Also, note, that there are compilers, where that flag is called differently, so that hard-coding it in `CMakeLists.txt` directly would prevent compilation.
* You should not specify any C++ flags for Fortran executables. Also, the Fortran option `-std=f2008` is compiler specific!
* If you wish to have compiler specific flags, we should put them into `config.cmake` in a compiler-dependent `if()` branch, like:
  ```cmake
  # Compiler specific settings
  if(("${CMAKE_Fortran_COMPILER_ID}" STREQUAL "GNU")
      set(FORTRAN_FLAGS "-std=2008"
          CACHE STRING "Extra flags for the Fortran compiler")
  elseif(("${CMAKE_Fortran_COMPILER_ID}" STREQUAL "Intel")
      set(FORTRAN_FLAGS "-stand f08"
          CACHE STRING "Extra flags for the Fortran compiler")
  endif()
  ```
  I'll make a separate PR for this.
* Last but not least, it would be good to integrate the testing possibility into the CMake framework. What is the correct way to run the tests?

**Comment by RKLindsey** [comment]
@aradi The "full" test suite can be run with `./run_tests.sh SHORT` in `serial_interface/tests`, but they take 10-15 minutes to run. However, I could modify the script to add a `if CI` type functionality, which only runs a single quick test for each API/compilation scheme - then, the time sink would just be compilation time.

**Comment by aradi** [comment]
OK, I see, thanks. I have to think, how to integrate with the CI.  For sure, we need a much shorter tests (max. 1-2 minute for all) for the CI. But also, the CMake test logic is usually the other way around: CMake driving individual tests (via `ctest`), so that you can for example run them easily in parallel. But that won't work with the current test script...

Anyway, you can merge my `hotfix3.suggestions` into `hotfix3` now, it consist of a single commit only.

**Pull request merged**
